// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PublicTask {
    "id": string;
    "run_id": string;
    "email": string;
    "status": Status;
    "user_code"?: string;
    "verification_url"?: string;
    "expires_at"?: string;
    "error"?: string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new PublicTask instance. */
    constructor($$source: Partial<PublicTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicTask instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicTask($$parsedSource as Partial<PublicTask>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusAuthorizing = "authorizing",
    StatusAuthorized = "authorized",
    StatusFailed = "failed",
};
