// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Workers {
    "s": number;
    "p": number;
    "c": number;
    "oauth": number;

    /** Creates a new Workers instance. */
    constructor($$source: Partial<Workers> = {}) {
        if (!("s" in $$source)) {
            this["s"] = 0;
        }
        if (!("p" in $$source)) {
            this["p"] = 0;
        }
        if (!("c" in $$source)) {
            this["c"] = 0;
        }
        if (!("oauth" in $$source)) {
            this["oauth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workers instance from a string or object.
     */
    static createFrom($$source: any = {}): Workers {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Workers($$parsedSource as Partial<Workers>);
    }
}
