// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Workers {
    /**
     * Creates a new Workers instance.
     * @param {Partial<Workers>} [$$source = {}] - The source object to create the Workers.
     */
    constructor($$source = {}) {
        if (!("s" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["s"] = 0;
        }
        if (!("p" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p"] = 0;
        }
        if (!("c" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["c"] = 0;
        }
        if (!("oauth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["oauth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workers instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workers}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Workers(/** @type {Partial<Workers>} */($$parsedSource));
    }
}
