// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../../internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as manualoauth$0 from "../../internal/manualoauth/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.BootstrapInfo>}
 */
export function Bootstrap() {
    return $Call.ByID(2934747687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.AccountHealthSummary>}
 */
export function CheckGatewayAccounts() {
    return $Call.ByID(2244012681).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearGatewayRequestLogs() {
    return $Call.ByID(1063812684);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.CreatedAPIKey>}
 */
export function CreateAPIKey(name) {
    return $Call.ByID(2849228272, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAPIKey(id) {
    return $Call.ByID(535668967, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGatewayAccount(id) {
    return $Call.ByID(251294873, id);
}

/**
 * ExportGatewayAccounts exports every gateway account as a re-importable CPA
 * JSON document and bundles them into a zip at destPath. Credentials are stored
 * encrypted at rest; only the store can decrypt them, so export must run here.
 * @param {string} destPath
 * @returns {$CancellablePromise<$models.GatewayAccountExportResult>}
 */
export function ExportGatewayAccounts(destPath) {
    return $Call.ByID(2432170069, destPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.Status>}
 */
export function GatewayStatus() {
    return $Call.ByID(1419683181).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<string>}
 */
export function GetAPIKeySecret(id) {
    return $Call.ByID(1639655270, id);
}

/**
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function GetDashboard() {
    return $Call.ByID(353919147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(303360312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.GatewayAccountImportResult>}
 */
export function ImportGatewayAccounts(paths) {
    return $Call.ByID(2318896960, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.APIKey[]>}
 */
export function ListAPIKeys() {
    return $Call.ByID(1193353329).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.Account[]>}
 */
export function ListGatewayAccounts() {
    return $Call.ByID(518095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.Model[]>}
 */
export function ListGatewayModels() {
    return $Call.ByID(3640931529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<gateway$0.RequestLog[]>}
 */
export function ListGatewayRequestLogs(limit) {
    return $Call.ByID(1644008471, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @returns {$CancellablePromise<manualoauth$0.PublicTask[]>}
 */
export function ListManualOAuthTasks() {
    return $Call.ByID(2595549062).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<$models.RunEntry[]>}
 */
export function ListRuns(limit) {
    return $Call.ByID(2950642485, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfig() {
    return $Call.ByID(81071333);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(3590639472, path);
}

/**
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(16531267, settings);
}

/**
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIKeyEnabled(id, enabled) {
    return $Call.ByID(2552370103, id, enabled);
}

/**
 * @param {$models.StartRequest} request
 * @returns {$CancellablePromise<$models.StartResult>}
 */
export function Start(request) {
    return $Call.ByID(3115171033, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartGateway() {
    return $Call.ByID(559468485);
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<manualoauth$0.PublicTask>}
 */
export function StartManualOAuth(taskID) {
    return $Call.ByID(1870308934, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2040913075);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopGateway() {
    return $Call.ByID(1172643219);
}

/**
 * @param {number} maxBytes
 * @returns {$CancellablePromise<string>}
 */
export function TailLog(maxBytes) {
    return $Call.ByID(1942471693, maxBytes);
}

/**
 * @param {$models.GatewayAccountUpdate} update
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGatewayAccount(update) {
    return $Call.ByID(2668249371, update);
}

// Private type creation functions
const $$createType0 = $models.BootstrapInfo.createFrom;
const $$createType1 = gateway$0.AccountHealthSummary.createFrom;
const $$createType2 = $models.CreatedAPIKey.createFrom;
const $$createType3 = $models.GatewayAccountExportResult.createFrom;
const $$createType4 = gateway$0.Status.createFrom;
const $$createType5 = $models.Dashboard.createFrom;
const $$createType6 = $models.Settings.createFrom;
const $$createType7 = $models.GatewayAccountImportResult.createFrom;
const $$createType8 = gateway$0.APIKey.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = gateway$0.Account.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = gateway$0.Model.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = gateway$0.RequestLog.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = manualoauth$0.PublicTask.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.RunEntry.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.StartResult.createFrom;
