// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../../internal/gateway/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.BootstrapInfo>}
 */
export function Bootstrap() {
    return $Call.ByID(2934747687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.CreatedAPIKey>}
 */
export function CreateAPIKey(name) {
    return $Call.ByID(2849228272, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAPIKey(id) {
    return $Call.ByID(535668967, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGatewayAccount(id) {
    return $Call.ByID(251294873, id);
}

/**
 * @returns {$CancellablePromise<gateway$0.Status>}
 */
export function GatewayStatus() {
    return $Call.ByID(1419683181).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function GetDashboard() {
    return $Call.ByID(353919147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(303360312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.APIKey[]>}
 */
export function ListAPIKeys() {
    return $Call.ByID(1193353329).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.Account[]>}
 */
export function ListGatewayAccounts() {
    return $Call.ByID(518095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.Model[]>}
 */
export function ListGatewayModels() {
    return $Call.ByID(3640931529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<$models.RunEntry[]>}
 */
export function ListRuns(limit) {
    return $Call.ByID(2950642485, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfig() {
    return $Call.ByID(81071333);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(3590639472, path);
}

/**
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(16531267, settings);
}

/**
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAPIKeyEnabled(id, enabled) {
    return $Call.ByID(2552370103, id, enabled);
}

/**
 * @param {$models.StartRequest} request
 * @returns {$CancellablePromise<$models.StartResult>}
 */
export function Start(request) {
    return $Call.ByID(3115171033, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartGateway() {
    return $Call.ByID(559468485);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2040913075);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopGateway() {
    return $Call.ByID(1172643219);
}

/**
 * @param {number} maxBytes
 * @returns {$CancellablePromise<string>}
 */
export function TailLog(maxBytes) {
    return $Call.ByID(1942471693, maxBytes);
}

/**
 * @param {$models.GatewayAccountUpdate} update
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGatewayAccount(update) {
    return $Call.ByID(2668249371, update);
}

// Private type creation functions
const $$createType0 = $models.BootstrapInfo.createFrom;
const $$createType1 = $models.CreatedAPIKey.createFrom;
const $$createType2 = gateway$0.Status.createFrom;
const $$createType3 = $models.Dashboard.createFrom;
const $$createType4 = $models.Settings.createFrom;
const $$createType5 = gateway$0.APIKey.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = gateway$0.Account.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = gateway$0.Model.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.RunEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.StartResult.createFrom;
