// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.BootstrapInfo>}
 */
export function Bootstrap() {
    return $Call.ByID(2934747687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function GetDashboard() {
    return $Call.ByID(353919147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(303360312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<$models.RunEntry[]>}
 */
export function ListRuns(limit) {
    return $Call.ByID(2950642485, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfig() {
    return $Call.ByID(81071333);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(path) {
    return $Call.ByID(3590639472, path);
}

/**
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(16531267, settings);
}

/**
 * @param {$models.StartRequest} request
 * @returns {$CancellablePromise<$models.StartResult>}
 */
export function Start(request) {
    return $Call.ByID(3115171033, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2040913075);
}

/**
 * @param {number} maxBytes
 * @returns {$CancellablePromise<string>}
 */
export function TailLog(maxBytes) {
    return $Call.ByID(1942471693, maxBytes);
}

// Private type creation functions
const $$createType0 = $models.BootstrapInfo.createFrom;
const $$createType1 = $models.Dashboard.createFrom;
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $models.RunEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.StartResult.createFrom;
