// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../../internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../../internal/state/models.js";

export class BootstrapInfo {
    /**
     * Creates a new BootstrapInfo instance.
     * @param {Partial<BootstrapInfo>} [$$source = {}] - The source object to create the BootstrapInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("data_root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data_root"] = "";
        }
        if (!("config_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config_path"] = "";
        }
        if (!("output_root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_root"] = "";
        }
        if (!("chrome_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chrome_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapInfo(/** @type {Partial<BootstrapInfo>} */($$parsedSource));
    }
}

export class CreatedAPIKey {
    /**
     * Creates a new CreatedAPIKey instance.
     * @param {Partial<CreatedAPIKey>} [$$source = {}] - The source object to create the CreatedAPIKey.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {gateway$0.APIKey}
             */
            this["key"] = (new gateway$0.APIKey());
        }
        if (!("secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedAPIKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreatedAPIKey}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("key" in $$parsedSource) {
            $$parsedSource["key"] = $$createField0_0($$parsedSource["key"]);
        }
        return new CreatedAPIKey(/** @type {Partial<CreatedAPIKey>} */($$parsedSource));
    }
}

export class Dashboard {
    /**
     * Creates a new Dashboard instance.
     * @param {Partial<Dashboard>} [$$source = {}] - The source object to create the Dashboard.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("sso_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sso_count"] = 0;
        }
        if (!("oauth_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["oauth_count"] = 0;
        }
        if (!("fail_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fail_count"] = 0;
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("phase_detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase_detail"] = "";
        }
        if (!("workers" in $$source)) {
            /**
             * @member
             * @type {state$0.Workers}
             */
            this["workers"] = (new state$0.Workers());
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("log_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_dir"] = "";
        }
        if (!("rate_per_min" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rate_per_min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dashboard}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workers" in $$parsedSource) {
            $$parsedSource["workers"] = $$createField10_0($$parsedSource["workers"]);
        }
        return new Dashboard(/** @type {Partial<Dashboard>} */($$parsedSource));
    }
}

export class GatewayAccountImportFailure {
    /**
     * Creates a new GatewayAccountImportFailure instance.
     * @param {Partial<GatewayAccountImportFailure>} [$$source = {}] - The source object to create the GatewayAccountImportFailure.
     */
    constructor($$source = {}) {
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountImportFailure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayAccountImportFailure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayAccountImportFailure(/** @type {Partial<GatewayAccountImportFailure>} */($$parsedSource));
    }
}

export class GatewayAccountImportResult {
    /**
     * Creates a new GatewayAccountImportResult instance.
     * @param {Partial<GatewayAccountImportResult>} [$$source = {}] - The source object to create the GatewayAccountImportResult.
     */
    constructor($$source = {}) {
        if (!("selected_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["selected_files"] = 0;
        }
        if (!("successful_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["successful_files"] = 0;
        }
        if (!("failed_files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed_files"] = 0;
        }
        if (!("imported_accounts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["imported_accounts"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {GatewayAccountImportFailure[]}
             */
            this["failures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayAccountImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField4_0($$parsedSource["failures"]);
        }
        return new GatewayAccountImportResult(/** @type {Partial<GatewayAccountImportResult>} */($$parsedSource));
    }
}

export class GatewayAccountUpdate {
    /**
     * Creates a new GatewayAccountUpdate instance.
     * @param {Partial<GatewayAccountUpdate>} [$$source = {}] - The source object to create the GatewayAccountUpdate.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("max_concurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_concurrent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewayAccountUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayAccountUpdate(/** @type {Partial<GatewayAccountUpdate>} */($$parsedSource));
    }
}

export class RunEntry {
    /**
     * Creates a new RunEntry instance.
     * @param {Partial<RunEntry>} [$$source = {}] - The source object to create the RunEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("cpa_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpa_count"] = 0;
        }
        if (!("sso_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sso_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunEntry(/** @type {Partial<RunEntry>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("email_mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email_mode"] = "";
        }
        if (!("email_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email_domain"] = "";
        }
        if (!("email_api" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email_api"] = "";
        }
        if (!("register_proxy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["register_proxy"] = "";
        }
        if (!("clearance_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clearance_enabled"] = false;
        }
        if (!("flaresolverr_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flaresolverr_url"] = "";
        }
        if (!("turnstile_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["turnstile_provider"] = "";
        }
        if (!("lite_solver_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lite_solver_url"] = "";
        }
        if (!("cpa_upload_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cpa_upload_enabled"] = false;
        }
        if (!("cpa_management_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cpa_management_base"] = "";
        }
        if (!("api_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["api_enabled"] = false;
        }
        if (!("api_listen_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_listen_host"] = "";
        }
        if (!("api_listen_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["api_listen_port"] = 0;
        }
        if (!("api_stream_default" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["api_stream_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class StartRequest {
    /**
     * Creates a new StartRequest instance.
     * @param {Partial<StartRequest>} [$$source = {}] - The source object to create the StartRequest.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target"] = 0;
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartRequest(/** @type {Partial<StartRequest>} */($$parsedSource));
    }
}

export class StartResult {
    /**
     * Creates a new StartResult instance.
     * @param {Partial<StartResult>} [$$source = {}] - The source object to create the StartResult.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("run_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["run_id"] = "";
        }
        if (!("log_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartResult(/** @type {Partial<StartResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = gateway$0.APIKey.createFrom;
const $$createType1 = state$0.Workers.createFrom;
const $$createType2 = GatewayAccountImportFailure.createFrom;
const $$createType3 = $Create.Array($$createType2);
