// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../../internal/state/models.js";

export class BootstrapInfo {
    "name": string;
    "version": string;
    "platform": string;
    "data_root": string;
    "config_path": string;
    "output_root": string;
    "chrome_path": string;

    /** Creates a new BootstrapInfo instance. */
    constructor($$source: Partial<BootstrapInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("data_root" in $$source)) {
            this["data_root"] = "";
        }
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("output_root" in $$source)) {
            this["output_root"] = "";
        }
        if (!("chrome_path" in $$source)) {
            this["chrome_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BootstrapInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapInfo($$parsedSource as Partial<BootstrapInfo>);
    }
}

export class Dashboard {
    "status": string;
    "running": boolean;
    "run_id": string;
    "target": number;
    "done": number;
    "sso_count": number;
    "oauth_count": number;
    "fail_count": number;
    "phase": string;
    "phase_detail": string;
    "workers": state$0.Workers;
    "pid": number;
    "started_at": string;
    "updated_at": string;
    "error": string;
    "log_path": string;
    "output_dir": string;
    "rate_per_min": number;

    /** Creates a new Dashboard instance. */
    constructor($$source: Partial<Dashboard> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("sso_count" in $$source)) {
            this["sso_count"] = 0;
        }
        if (!("oauth_count" in $$source)) {
            this["oauth_count"] = 0;
        }
        if (!("fail_count" in $$source)) {
            this["fail_count"] = 0;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("phase_detail" in $$source)) {
            this["phase_detail"] = "";
        }
        if (!("workers" in $$source)) {
            this["workers"] = (new state$0.Workers());
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("log_path" in $$source)) {
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            this["output_dir"] = "";
        }
        if (!("rate_per_min" in $$source)) {
            this["rate_per_min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     */
    static createFrom($$source: any = {}): Dashboard {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workers" in $$parsedSource) {
            $$parsedSource["workers"] = $$createField10_0($$parsedSource["workers"]);
        }
        return new Dashboard($$parsedSource as Partial<Dashboard>);
    }
}

export class RunEntry {
    "id": string;
    "path": string;
    "updated_at": string;
    "cpa_count": number;
    "sso_count": number;

    /** Creates a new RunEntry instance. */
    constructor($$source: Partial<RunEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("cpa_count" in $$source)) {
            this["cpa_count"] = 0;
        }
        if (!("sso_count" in $$source)) {
            this["sso_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RunEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunEntry($$parsedSource as Partial<RunEntry>);
    }
}

export class Settings {
    "email_mode": string;
    "email_domain": string;
    "email_api": string;
    "register_proxy": string;
    "clearance_enabled": boolean;
    "flaresolverr_url": string;
    "turnstile_provider": string;
    "lite_solver_url": string;
    "cpa_upload_enabled": boolean;
    "cpa_management_base": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("email_mode" in $$source)) {
            this["email_mode"] = "";
        }
        if (!("email_domain" in $$source)) {
            this["email_domain"] = "";
        }
        if (!("email_api" in $$source)) {
            this["email_api"] = "";
        }
        if (!("register_proxy" in $$source)) {
            this["register_proxy"] = "";
        }
        if (!("clearance_enabled" in $$source)) {
            this["clearance_enabled"] = false;
        }
        if (!("flaresolverr_url" in $$source)) {
            this["flaresolverr_url"] = "";
        }
        if (!("turnstile_provider" in $$source)) {
            this["turnstile_provider"] = "";
        }
        if (!("lite_solver_url" in $$source)) {
            this["lite_solver_url"] = "";
        }
        if (!("cpa_upload_enabled" in $$source)) {
            this["cpa_upload_enabled"] = false;
        }
        if (!("cpa_management_base" in $$source)) {
            this["cpa_management_base"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class StartRequest {
    "target": number;
    "threads": number;

    /** Creates a new StartRequest instance. */
    constructor($$source: Partial<StartRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = 0;
        }
        if (!("threads" in $$source)) {
            this["threads"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartRequest($$parsedSource as Partial<StartRequest>);
    }
}

export class StartResult {
    "pid": number;
    "run_id": string;
    "log_path": string;
    "output_dir": string;

    /** Creates a new StartResult instance. */
    constructor($$source: Partial<StartResult> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("log_path" in $$source)) {
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            this["output_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartResult($$parsedSource as Partial<StartResult>);
    }
}

// Private type creation functions
const $$createType0 = state$0.Workers.createFrom;
