// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../../internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../../internal/state/models.js";

export class BootstrapInfo {
    "name": string;
    "version": string;
    "platform": string;
    "data_root": string;
    "config_path": string;
    "output_root": string;
    "chrome_path": string;

    /** Creates a new BootstrapInfo instance. */
    constructor($$source: Partial<BootstrapInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("data_root" in $$source)) {
            this["data_root"] = "";
        }
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("output_root" in $$source)) {
            this["output_root"] = "";
        }
        if (!("chrome_path" in $$source)) {
            this["chrome_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BootstrapInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapInfo($$parsedSource as Partial<BootstrapInfo>);
    }
}

export class CreatedAPIKey {
    "key": gateway$0.APIKey;
    "secret": string;

    /** Creates a new CreatedAPIKey instance. */
    constructor($$source: Partial<CreatedAPIKey> = {}) {
        if (!("key" in $$source)) {
            this["key"] = (new gateway$0.APIKey());
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedAPIKey instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedAPIKey {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("key" in $$parsedSource) {
            $$parsedSource["key"] = $$createField0_0($$parsedSource["key"]);
        }
        return new CreatedAPIKey($$parsedSource as Partial<CreatedAPIKey>);
    }
}

export class Dashboard {
    "status": string;
    "running": boolean;
    "run_id": string;
    "target": number;
    "done": number;
    "sso_count": number;
    "oauth_count": number;
    "fail_count": number;
    "phase": string;
    "phase_detail": string;
    "workers": state$0.Workers;
    "pid": number;
    "started_at": string;
    "updated_at": string;
    "error": string;
    "log_path": string;
    "output_dir": string;
    "rate_per_min": number;

    /** Creates a new Dashboard instance. */
    constructor($$source: Partial<Dashboard> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("sso_count" in $$source)) {
            this["sso_count"] = 0;
        }
        if (!("oauth_count" in $$source)) {
            this["oauth_count"] = 0;
        }
        if (!("fail_count" in $$source)) {
            this["fail_count"] = 0;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("phase_detail" in $$source)) {
            this["phase_detail"] = "";
        }
        if (!("workers" in $$source)) {
            this["workers"] = (new state$0.Workers());
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("log_path" in $$source)) {
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            this["output_dir"] = "";
        }
        if (!("rate_per_min" in $$source)) {
            this["rate_per_min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     */
    static createFrom($$source: any = {}): Dashboard {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workers" in $$parsedSource) {
            $$parsedSource["workers"] = $$createField10_0($$parsedSource["workers"]);
        }
        return new Dashboard($$parsedSource as Partial<Dashboard>);
    }
}

export class GatewayAccountImportFailure {
    "file": string;
    "error": string;

    /** Creates a new GatewayAccountImportFailure instance. */
    constructor($$source: Partial<GatewayAccountImportFailure> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountImportFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayAccountImportFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayAccountImportFailure($$parsedSource as Partial<GatewayAccountImportFailure>);
    }
}

export class GatewayAccountImportResult {
    "selected_files": number;
    "successful_files": number;
    "failed_files": number;
    "imported_accounts": number;
    "failures": GatewayAccountImportFailure[];

    /** Creates a new GatewayAccountImportResult instance. */
    constructor($$source: Partial<GatewayAccountImportResult> = {}) {
        if (!("selected_files" in $$source)) {
            this["selected_files"] = 0;
        }
        if (!("successful_files" in $$source)) {
            this["successful_files"] = 0;
        }
        if (!("failed_files" in $$source)) {
            this["failed_files"] = 0;
        }
        if (!("imported_accounts" in $$source)) {
            this["imported_accounts"] = 0;
        }
        if (!("failures" in $$source)) {
            this["failures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayAccountImportResult {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("failures" in $$parsedSource) {
            $$parsedSource["failures"] = $$createField4_0($$parsedSource["failures"]);
        }
        return new GatewayAccountImportResult($$parsedSource as Partial<GatewayAccountImportResult>);
    }
}

export class GatewayAccountUpdate {
    "id": number;
    "name": string;
    "enabled": boolean;
    "max_concurrent": number;

    /** Creates a new GatewayAccountUpdate instance. */
    constructor($$source: Partial<GatewayAccountUpdate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("max_concurrent" in $$source)) {
            this["max_concurrent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAccountUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayAccountUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayAccountUpdate($$parsedSource as Partial<GatewayAccountUpdate>);
    }
}

export class RunEntry {
    "id": string;
    "path": string;
    "updated_at": string;
    "cpa_count": number;
    "sso_count": number;

    /** Creates a new RunEntry instance. */
    constructor($$source: Partial<RunEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("cpa_count" in $$source)) {
            this["cpa_count"] = 0;
        }
        if (!("sso_count" in $$source)) {
            this["sso_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RunEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunEntry($$parsedSource as Partial<RunEntry>);
    }
}

export class Settings {
    "email_mode": string;
    "email_domain": string;
    "email_api": string;
    "register_proxy": string;
    "clearance_enabled": boolean;
    "flaresolverr_url": string;
    "turnstile_provider": string;
    "lite_solver_url": string;
    "cpa_upload_enabled": boolean;
    "cpa_management_base": string;
    "api_enabled": boolean;
    "api_listen_host": string;
    "api_listen_port": number;
    "api_stream_default": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("email_mode" in $$source)) {
            this["email_mode"] = "";
        }
        if (!("email_domain" in $$source)) {
            this["email_domain"] = "";
        }
        if (!("email_api" in $$source)) {
            this["email_api"] = "";
        }
        if (!("register_proxy" in $$source)) {
            this["register_proxy"] = "";
        }
        if (!("clearance_enabled" in $$source)) {
            this["clearance_enabled"] = false;
        }
        if (!("flaresolverr_url" in $$source)) {
            this["flaresolverr_url"] = "";
        }
        if (!("turnstile_provider" in $$source)) {
            this["turnstile_provider"] = "";
        }
        if (!("lite_solver_url" in $$source)) {
            this["lite_solver_url"] = "";
        }
        if (!("cpa_upload_enabled" in $$source)) {
            this["cpa_upload_enabled"] = false;
        }
        if (!("cpa_management_base" in $$source)) {
            this["cpa_management_base"] = "";
        }
        if (!("api_enabled" in $$source)) {
            this["api_enabled"] = false;
        }
        if (!("api_listen_host" in $$source)) {
            this["api_listen_host"] = "";
        }
        if (!("api_listen_port" in $$source)) {
            this["api_listen_port"] = 0;
        }
        if (!("api_stream_default" in $$source)) {
            this["api_stream_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class StartRequest {
    "target": number;
    "threads": number;

    /** Creates a new StartRequest instance. */
    constructor($$source: Partial<StartRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = 0;
        }
        if (!("threads" in $$source)) {
            this["threads"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartRequest($$parsedSource as Partial<StartRequest>);
    }
}

export class StartResult {
    "pid": number;
    "run_id": string;
    "log_path": string;
    "output_dir": string;

    /** Creates a new StartResult instance. */
    constructor($$source: Partial<StartResult> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("run_id" in $$source)) {
            this["run_id"] = "";
        }
        if (!("log_path" in $$source)) {
            this["log_path"] = "";
        }
        if (!("output_dir" in $$source)) {
            this["output_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartResult instance from a string or object.
     */
    static createFrom($$source: any = {}): StartResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartResult($$parsedSource as Partial<StartResult>);
    }
}

// Private type creation functions
const $$createType0 = gateway$0.APIKey.createFrom;
const $$createType1 = state$0.Workers.createFrom;
const $$createType2 = GatewayAccountImportFailure.createFrom;
const $$createType3 = $Create.Array($$createType2);
