// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIKey contains only the public metadata stored for a client key.
 */
export class APIKey {
    /**
     * Creates a new APIKey instance.
     * @param {Partial<APIKey>} [$$source = {}] - The source object to create the APIKey.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prefix"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_used_at"] = undefined;
        }
        if (!("has_secret" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_secret"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APIKey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIKey(/** @type {Partial<APIKey>} */($$parsedSource));
    }
}

/**
 * Account is the non-secret account state exposed to the desktop UI.
 */
export class Account {
    /**
     * Creates a new Account instance.
     * @param {Partial<Account>} [$$source = {}] - The source object to create the Account.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_id"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("auth_status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["auth_status"] = "";
        }
        if (!("max_concurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_concurrent"] = 0;
        }
        if (!("failure_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failure_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["cooldown_until"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_used_at"] = undefined;
        }
        if (!("observed_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["observed_model"] = "";
        }
        if (!("health_status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["health_status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_checked_at"] = undefined;
        }
        if (!("health_latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["health_latency_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["health_error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["expires_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Account}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account(/** @type {Partial<Account>} */($$parsedSource));
    }
}

export class AccountHealthSummary {
    /**
     * Creates a new AccountHealthSummary instance.
     * @param {Partial<AccountHealthSummary>} [$$source = {}] - The source object to create the AccountHealthSummary.
     */
    constructor($$source = {}) {
        if (!("checked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["checked"] = 0;
        }
        if (!("healthy" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["healthy"] = 0;
        }
        if (!("unhealthy" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unhealthy"] = 0;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("completed_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["completed_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountHealthSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountHealthSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountHealthSummary(/** @type {Partial<AccountHealthSummary>} */($$parsedSource));
    }
}

export class Model {
    /**
     * Creates a new Model instance.
     * @param {Partial<Model>} [$$source = {}] - The source object to create the Model.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("object" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["object"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created"] = 0;
        }
        if (!("owned_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owned_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Model}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model(/** @type {Partial<Model>} */($$parsedSource));
    }
}

export class RequestLog {
    /**
     * Creates a new RequestLog instance.
     * @param {Partial<RequestLog>} [$$source = {}] - The source object to create the RequestLog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["account_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["user_agent"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestLog(/** @type {Partial<RequestLog>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}
