// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIKey contains only the public metadata stored for a client key.
 */
export class APIKey {
    "id": number;
    "name": string;
    "prefix": string;
    "enabled": boolean;
    "created_at": string;
    "last_used_at"?: string | null;
    "has_secret": boolean;

    /** Creates a new APIKey instance. */
    constructor($$source: Partial<APIKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("has_secret" in $$source)) {
            this["has_secret"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIKey instance from a string or object.
     */
    static createFrom($$source: any = {}): APIKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIKey($$parsedSource as Partial<APIKey>);
    }
}

/**
 * Account is the non-secret account state exposed to the desktop UI.
 */
export class Account {
    "id": number;
    "provider": string;
    "name": string;
    "email": string;
    "user_id": string;
    "enabled": boolean;
    "auth_status": string;
    "max_concurrent": number;
    "failure_count": number;
    "cooldown_until"?: string | null;
    "last_used_at"?: string | null;
    "observed_model": string;
    "health_status": string;
    "last_checked_at"?: string | null;
    "health_latency_ms": number;
    "health_error"?: string;
    "expires_at"?: string | null;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("auth_status" in $$source)) {
            this["auth_status"] = "";
        }
        if (!("max_concurrent" in $$source)) {
            this["max_concurrent"] = 0;
        }
        if (!("failure_count" in $$source)) {
            this["failure_count"] = 0;
        }
        if (!("observed_model" in $$source)) {
            this["observed_model"] = "";
        }
        if (!("health_status" in $$source)) {
            this["health_status"] = "";
        }
        if (!("health_latency_ms" in $$source)) {
            this["health_latency_ms"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

export class AccountHealthSummary {
    "checked": number;
    "healthy": number;
    "unhealthy": number;
    "started_at": string;
    "completed_at": string;

    /** Creates a new AccountHealthSummary instance. */
    constructor($$source: Partial<AccountHealthSummary> = {}) {
        if (!("checked" in $$source)) {
            this["checked"] = 0;
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = 0;
        }
        if (!("unhealthy" in $$source)) {
            this["unhealthy"] = 0;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("completed_at" in $$source)) {
            this["completed_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountHealthSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountHealthSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountHealthSummary($$parsedSource as Partial<AccountHealthSummary>);
    }
}

export class Model {
    "id": string;
    "object": string;
    "created": number;
    "owned_by": string;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

export class RequestLog {
    "id": number;
    "timestamp": string;
    "method": string;
    "path": string;
    "status": number;
    "duration_ms": number;
    "model"?: string;
    "account_id"?: number;
    "user_agent"?: string;

    /** Creates a new RequestLog instance. */
    constructor($$source: Partial<RequestLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestLog instance from a string or object.
     */
    static createFrom($$source: any = {}): RequestLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestLog($$parsedSource as Partial<RequestLog>);
    }
}

export class Status {
    "running": boolean;
    "address": string;
    "error"?: string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
